"""Create cleaned event tables and a reproducible data-quality report."""

import argparse
import csv
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

import pandas as pd


KEY_COLUMNS = [
    "FRA Number", "Crossing Name", "Latitude", "Longitude",
    "blockageDate", "blockageStartTime", "duration (min)",
]


def parse_args() -> argparse.Namespace:
    """Parse input and output paths for the report-preparation workflow."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path(__file__).parent)
    parser.add_argument("--all-input", type=Path)
    parser.add_argument("--eight-input", type=Path)
    return parser.parse_args()


def parse_start(row: dict[str, str]) -> datetime:
    """Parse an event's date and start time into one timestamp."""
    date_value = datetime.strptime(row["blockageDate"], "%m/%d/%Y").date()
    for time_format in ("%H:%M:%S", "%H:%M"):
        try:
            return datetime.strptime(
                f"{date_value} {row['blockageStartTime']}",
                f"%Y-%m-%d {time_format}",
            )
        except ValueError:
            continue
    raise ValueError(f"Invalid event time: {row['blockageDate']} {row['blockageStartTime']}")


def clean_events(rows: list[dict[str, str]]) -> tuple[list[dict[str, str]], int, int]:
    """Remove invalid durations and exact duplicate event keys.

    Returns:
        Clean rows, number of invalid rows, and number of duplicate rows removed.
    """
    clean_rows = []
    seen = set()
    invalid_count = 0
    duplicate_count = 0
    for row in rows:
        try:
            duration = float(row["duration (min)"])
            start = parse_start(row)
            if duration <= 0:
                raise ValueError("nonpositive duration")
        except (KeyError, TypeError, ValueError):
            invalid_count += 1
            continue
        key = tuple(row[field] for field in KEY_COLUMNS)
        if key in seen:
            duplicate_count += 1
            continue
        seen.add(key)
        end = start + timedelta(minutes=duration)
        output = {field: row.get(field, "") for field in row if field}
        output["blockageEndDate"] = f"{end.month}/{end.day}/{end.year}"
        output["blockageEndTime"] = end.strftime("%H:%M:%S")
        clean_rows.append(output)
    return clean_rows, invalid_count, duplicate_count


def read_rows(path: Path) -> list[dict[str, str]]:
    """Read a CSV with the repository's UTF-8/BOM convention."""
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def write_rows(path: Path, rows: list[dict[str, str]]) -> None:
    """Write cleaned rows using the fields present in the first row."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = list(rows[0].keys()) if rows else []
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def resolve_input(explicit: Optional[Path], preferred: Path, legacy: Path) -> Path:
    """Use an explicit path, then the current processed output, then legacy data."""
    candidates = [explicit] if explicit else [preferred, legacy]
    for candidate in candidates:
        if candidate and candidate.exists():
            return candidate
    raise FileNotFoundError("No input found. Run the TrainFo refresh first or pass an input path.")


def main() -> int:
    """Create cleaned report artifacts and print before/after counts."""
    args = parse_args()
    root = args.project_root
    report_dir = root / "initial_report"
    all_input = resolve_input(
        args.all_input,
        root / "data/processed/trainfo_houston_all_latest.csv",
        root / "trainfo_merged_w_coords8(in).csv",
    )
    eight_input = resolve_input(
        args.eight_input,
        root / "data/processed/trainfo_houston_8streets_latest.csv",
        root / "trainfo_merged_w_coords8_8streets.csv",
    )
    summaries = []
    for label, input_path in (("all", all_input), ("8streets", eight_input)):
        raw_rows = read_rows(input_path)
        clean_rows, invalid_count, duplicate_count = clean_events(raw_rows)
        output_path = report_dir / f"trainfo_{label}_events_clean.csv"
        write_rows(output_path, clean_rows)
        summaries.append((label, len(raw_rows), len(clean_rows), invalid_count, duplicate_count))

    report_path = report_dir / "trainfo_initial_data_report.md"
    lines = [
        "# Initial TrainFo Data Report", "",
        "This report is generated by `prepare_initial_report.py` from the downloaded event tables.", "",
        "| Dataset | Raw rows | Clean rows | Invalid durations | Duplicate rows removed |",
        "|---|---:|---:|---:|---:|",
    ]
    for label, raw_count, clean_count, invalid_count, duplicate_count in summaries:
        lines.append(f"| {label} | {raw_count:,} | {clean_count:,} | {invalid_count:,} | {duplicate_count:,} |")
    lines.extend([
        "", "## Cleaning rules", "",
        "- Exact duplicate event keys are kept once.",
        "- Missing, invalid, or nonpositive durations are excluded.",
        "- Long durations are retained for investigation rather than deleted automatically.",
        "- Sensor gaps are not imputed; absence of an event does not prove a crossing was clear.",
        "", "The cleaned event tables are not yet the minute-level modeling matrix. The modeling workflow must define sensor-gap handling, a synchronized state grid, historical and neighboring-crossing features, and 5/10/15/30-minute targets without future leakage.",
    ])
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {report_path}")
    for summary in summaries:
        print(summary)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
